### ISSUE TITLE
Code main navigation toolbar

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#13]
# App navigation toolbar
Create a navbar for the website. Implementation should be based on the [Figma design](https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Sac-Website?type=design&node-id=375%3A390&mode=design&t=9KFdLi1BmyJcnfK4-1). It should be responsive and collapse the main links on mobile. Extended dropdown menu button (hide/show) with button on the right side.

### Improvements to be made:

- [x] Desktop
- [x] Mobile
- [ ] Add support for a banner to be shown.

### Tasks:

Add documentation in [Layouts_pages_and_components.md](https://github.com/code4sac/opensac.org/blob/main/public/documentation/Layouts_pages_and_components.md).

**Comment by natebass** [comment]
I am currently working on this.

**Comment by natebass** [comment]
I implemented some link animations and the desktop extended menu. It still needs to be responsive on mobile.

**Resolved.** There is a bug when switching to a not found page and back to home. The navbar background stays completely transparent. **Example:** Navigate to Contact then back to home in the navbar.

**Comment by feydan** [comment]
Closing as there is only one issue remaining referenced here.  We can use that one.
