### ISSUE TITLE
Figma designs

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#15]
Implement all Figma designs in the project source code.

Figma link: https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Sac-Website?type=design&node-id=292%3A576&mode=design&t=k1ryNcGVCpubFrDp-1

Remaining issues:

- [ ] https://github.com/code4sac/opensac.org/issues/68

**Comment by feydan** [comment]
Closing since there is only one issue left.  We can just use that one.
