### ISSUE TITLE
Get Started page

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#24]
Add page for Get Started [opensac.org/get-started](https://opensac.org/get-started).

Figma design is [here](https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Sac-Website?type=design&node-id=555-1091&mode=design&t=9KFdLi1BmyJcnfK4-0).

### Notes

We need to decide the links we should use for the following.

Meeting link: 
New member form:

**Comment by jSunpayco** [comment]
Will be working on it. Thanks.
https://github.com/jSunpayco/opensac.org/tree/get-started-page

**Comment by natebass** [comment]
Matches the Figma design. Merged in #37.

Thank you @jSunpayco.
