### ISSUE TITLE
Projects page

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#26]
Add page for Projects [opensac.org/projects](https://opensac.org/projects)

Figma design is [here](https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Sac-Website?type=design&node-id=1158-3581&mode=design&t=9KFdLi1BmyJcnfK4-0).

### Tasks

- [ ] Use MDX

**Comment by feydan** [comment]
There have been several merges looking to address this issue:
#53 #54 #56 #59
