### ISSUE TITLE
Code of Conduct page

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#29]
Add page for code of conduct [opensac.org/code-of-conduct](opensac.org/code-of-conduct).

Figma design is [here](https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Sac-Website?type=design&node-id=597-1100&mode=design&t=9KFdLi1BmyJcnfK4-0).

**Comment by jSunpayco** [comment]
https://github.com/jSunpayco/opensac.org/tree/code-of-conduct-page
Will start working on this. Thanks
