### ISSUE TITLE
Update Homepage - Collaborations and Partnerships

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#43]
Add a "collaborations and partnerships" section towards the bottom of the homepage. It has been added to the [Figma design](https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Sac-Website?type=design&node-id=375%3A390&mode=design&t=9KFdLi1BmyJcnfK4-1) for reference.

The component has a grey colored background. This might also be reused in other sections (see Code of Conduct - Anti-Harassment Email Reporting section).

**Comment by gautamjuyal** [comment]
Can i work on this issue?

**Comment by natebass** [comment]
@gautamjuyal Sorry for the late reply. This issue is resolved now. Feel free to take a look and see if you find any bugs or improvements. Thanks!

**Comment by gautamjuyal** [comment]
That's cool. Good thing the issue was resolved fast!
