### ISSUE TITLE
Add node engine version in package.json

### ISSUE THREAD

**Issue by feydan** [code4sac/opensac.org#49]
This will give developers a warning if they are using incorrect versions of node when installing the project.

I believe this project uses Node 18 or higher.

See the following for how to use it: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

**Comment by natebass** [comment]
Version >=20 was defined in this commit https://github.com/code4sac/opensac.org/pull/50/commits/204d438fab0a30731dfb3bbd72c2924c67a38bc5.

The project minimum Node version is 18.17 which is [required by Next.js 14](https://nextjs.org/docs/app/building-your-application/upgrading/version-14).
