### ISSUE TITLE
Add a linter and linting rules

### ISSUE THREAD

**Issue by feydan** [code4sac/opensac.org#61]
We want to make sure that all developers contributing to the code base save code in the same format so our IDEs don't fight each other on superficial formatting like spaces and newlines.

**Comment by Alisa1989** [comment]
how about this one:
[dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

**Comment by feydan** [comment]
> how about this one: [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

Yep this extension for vs code is good, but we will also need an eslint file in the repo, and maybe some instructions in the readme for using this extension.

I think we should also use [Prettier ](https://prettier.io/docs/en/install.html) and the [extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) for that too.  And also https://github.com/prettier/eslint-config-prettier#installation.

**Comment by Alisa1989** [comment]
looks like there is a way that Next wants us to do things: 
[linting in Next.js](https://nextjs.org/docs/pages/building-your-application/configuring/eslint)
There is also a section explaining how to use ESLint in conjunction with Prettier
I'll have a look into it next week.

**Comment by Alisa1989** [comment]
The linter works now and I removed initial errors with a commit.
The next commit will be to adjust the img tags to Image but it will be quite laborious as the width property needs to be modified. 
[https://stackoverflow.com/questions/75781160/next-image-component-gives-error-missing-required-width-property-when-runni](https://stackoverflow.com/questions/75781160/next-image-component-gives-error-missing-required-width-property-when-runni)
