### ISSUE TITLE
Single Project Page

### ISSUE THREAD

**Issue by autecht** [code4sac/opensac.org#65]
Finish dynamically loading and styling single project page.

- [x] Change styling (spacing, sizing, and borders) to more accurately reflect Figma design: https://www.figma.com/file/attWQWKwed1XSaaaMuzM5m/Open-Websites?type=design&node-id=292-576&mode=design&t=nKpvVXHRcRyTqUTk-0

- [x] Update styling to adapt to devices with small screens
- [x] Dynamically load Roadmap Progress Indicators to reflect Figma design:
 ![image](https://github.com/code4sac/opensac.org/assets/103269824/5e26f127-2a73-4ec1-b09e-391734c4c742)
- [x] Change blank Link component href for Get Started button in singleProjectsSectionStart.jsx to direct to appropriate webpage

**Comment by natebass** [comment]
I started an issue for the dynamic roadmap timeline functionality #75.
