### ISSUE TITLE
Project roadmap status

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#75]
The individual project page contains a roadmap timeline. It uses the roadmap object from [meta.yml](https://github.com/code4sac/opensac.org/blob/dd2da78cdd09cd752b9a95e4e86cd29fef55520a/meta.yml#L31C1-L31C9).

Currently, the design does not dynamically update. I imagine a solution in two ways. Let me know if anyone thinks of something different.

- Parse the dates from the `time_range` object and check if the current date is inside the range.
- Add a property, like `roadmap.research.progress`, and explicitly define the progress.

**Comment by natebass** [comment]
I am going to work on a testing suite before tackling this. With tests, I will use mock data so I don't hit the GitHub API limit.

**Comment by BSims623** [comment]
I think a came up with a solution for this. Just created a pull request.
