### ISSUE TITLE
Add favicon image

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#84]
Open Sacramento needs a favicon. It currently displays the default Next.js logo.

We can discuss the appropriate image and design.

**Comment by nicklisin** [comment]
I've created a vector icon for the favicon in SVG format, along with a couple of standard sizes in PNG.
The icon has been slightly modified (more whitespace has been added) to ensure readability at the small size of the favicon.

![code_sac_fav_256x256](https://github.com/code4sac/opensac.org/assets/40894913/a0f9c901-2423-48a0-bc88-2f9488243f1b)

![code_sac_fav_512x512](https://github.com/code4sac/opensac.org/assets/40894913/98d3f54d-6780-407f-9620-e671d01005df)

![code_sac_fav](https://github.com/code4sac/opensac.org/assets/40894913/a892ecde-7779-4b7e-825c-0762dd2225ff)

**Comment by Alisa1989** [comment]
Thanks Nick!
