### ISSUE TITLE
Add link to conflict resolution process

### ISSUE THREAD

**Issue by natebass** [code4sac/opensac.org#85]
Open Sacramento has a conflict resolution Google doc [here](https://docs.google.com/forms/d/1PvpQR1Tb1Y-fja1GOGp1ihJfLgCD0OKeUOkgmTwXKoQ/edit?ts=65df5401#settings). We can link to this at the bottom of the [code of conduct page](https://opensac.org/code-of-conduct) page.

**Comment by Alisa1989** [comment]
Should we have it added in the Figma first?
